### ISSUE TITLE
代码块部分后来有完成吗？貌似还是没有加上行号。官网上有个codelst包感觉还可以

### ISSUE THREAD

**Issue by hakureiR-eimu** [werifu/HUST-typst-template#13]
![image](https://github.com/werifu/HUST-typst-template/assets/94830231/3a300b9b-78cb-4ae4-b66a-290449b4fa87)
导入例 ``` #import "@preview/codelst:2.0.0": sourcecode ```
效果
![image](https://github.com/werifu/HUST-typst-template/assets/94830231/047b962e-3767-47fc-9fe4-6d2028e5b7ce)

**Comment by werifu** [comment]
这一部分没做的原因是发现华科在毕业设计里基本没对代码格式做规定，我觉得这个package效果可以，如果方便可以提个PR？

**Comment by hakureiR-eimu** [comment]
typst有像npm一样的包管理工具吗。感觉把官方的package仓库拉下来再粘贴过去太丑陋了，而且大小也不太合适

**Comment by werifu** [comment]
只需要 import 引入，编译时会自动下载的吧，不需要手动 `npm install xxx` 这样的
