### ISSUE TITLE
请问是否支持三线表？

### ISSUE THREAD

**Issue by KuangjuX** [werifu/HUST-typst-template#6]

**Comment by werifu** [comment]
模板暂时没有实现封装好的版本，不过用 typst 本身可以做到，模板中实现三线表在计划之中，或者如果有兴趣也可以自己实现后提PR
相关 issue：https://github.com/typst/typst/issues/131

**Comment by KuangjuX** [comment]
感谢，照着 https://github.com/typst/typst/issues/131#issuecomment-1479547933 实现了三线表并且提了 PR #7 ，希望 review 以下，我刚开始用 typst，可能写的不是很好

**Comment by werifu** [comment]
done at https://github.com/werifu/HUST-typst-template/pull/7
