### ISSUE TITLE
学院管理层同意么（狗头）

### ISSUE THREAD

**Issue by SKTT1Ryze** [werifu/HUST-typst-template#8]
华科校友，感觉毕业答辩的时候最看重的就是论文格式。

**Comment by werifu** [comment]
模板还在迭代中，所以还没跟上边说（虽然大萝卜应该好说话），格式不对可以调，跟 LaTeX 其实没本质区别，如果老板要求用 word 那照样没戏（

**Comment by SKTT1Ryze** [comment]
可以考虑让大萝卜把这个模版一起放到那个“xxx毕业答辩资料包”里，并周知答辩老师。这样就不怕论文写完了但老师们不认账。
