### ISSUE TITLE
目录页最后会多出来一页并有 `N` 的页码

### ISSUE THREAD

**Issue by KuangjuX** [werifu/HUST-typst-template#9]
![example](https://user-images.githubusercontent.com/56680481/232312926-fea54997-8654-4094-a16e-7052b92abe16.png)

**Comment by werifu** [comment]
这个是页面计数器为0导致的，之前toc一直自己多出来一页，可能是typst之前的bug，现在可以修复了，fixed。[d736699](https://github.com/werifu/HUST-typst-template/commit/d7366998d13ad7591812eb178f6610224b603399)
